CREATE TABLE IF NOT EXISTS sys_branch (
    id INT NOT NULL AUTO_INCREMENT,
    partybranchname VARCHAR(64) NOT NULL,
    establishtime DATE NULL,
    partynumber INT NULL,
    dept_id INT NULL,
    dept_name VARCHAR(64) NULL,
    branchuser_id INT NULL,
    branchuser_name VARCHAR(255) NULL,
    status CHAR(1) DEFAULT '0',
    create_by VARCHAR(64) DEFAULT '',
    create_time DATETIME NULL,
    update_by VARCHAR(64) DEFAULT '',
    update_time DATETIME NULL,
    remark VARCHAR(500) NULL,
    branch_secretary_id INT NULL,
    branch_secretary_name VARCHAR(255) NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_branch_star (
    id BIGINT NOT NULL AUTO_INCREMENT,
    sodsacs VARCHAR(20) NOT NULL,
    partybranchname VARCHAR(64) NOT NULL,
    establishtime DATE NULL,
    partynumber INT NULL,
    dept_id INT NULL,
    dept_name VARCHAR(64) NULL,
    branchuser_id INT NULL,
    branchuser_name VARCHAR(255) NULL,
    branch_secretary_id INT NULL,
    branch_secretary_name VARCHAR(255) NULL,
    self_star VARCHAR(255) NULL,
    context VARCHAR(1000) NULL,
    foundationitem INT NULL,
    pluses INT NULL,
    minuses INT NULL,
    score INT NULL,
    starrating VARCHAR(255) NULL,
    outcome VARCHAR(1000) NULL,
    del_flag CHAR(1) DEFAULT '0',
    organizationcomment VARCHAR(1000) NULL,
    comments VARCHAR(1000) NULL,
    process INT NULL,
    sb_year VARCHAR(20) NULL,
    file_name VARCHAR(255) NULL,
    file_path VARCHAR(500) NULL,
    ygly_id INT NULL,
    ygly_name VARCHAR(255) NULL,
    create_by VARCHAR(64) DEFAULT '',
    create_time DATETIME NULL,
    update_by VARCHAR(64) DEFAULT '',
    update_time DATETIME NULL,
    remark VARCHAR(500) NULL,
    commentitems INT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_user (
    user_id BIGINT NOT NULL AUTO_INCREMENT,
    dept_id BIGINT NULL,
    user_name VARCHAR(30) NOT NULL,
    nick_name VARCHAR(30) NOT NULL,
    user_type VARCHAR(2) DEFAULT '00',
    email VARCHAR(50) DEFAULT '',
    phonenumber VARCHAR(14) DEFAULT '',
    sex CHAR(1) DEFAULT '0',
    idcard VARCHAR(255) NULL,
    enterpartytime DATE NULL,
    origin VARCHAR(255) NULL,
    avatar VARCHAR(100) DEFAULT '',
    password VARCHAR(100) DEFAULT '',
    branch_id INT NULL,
    branch_name VARCHAR(255) NULL,
    post_id VARCHAR(255) NULL,
    post_name VARCHAR(255) NULL,
    status CHAR(1) DEFAULT '0',
    del_flag CHAR(1) DEFAULT '0',
    login_ip VARCHAR(128) DEFAULT '',
    login_date DATETIME NULL,
    create_by VARCHAR(64) DEFAULT '',
    create_time DATETIME NULL,
    update_by VARCHAR(64) DEFAULT '',
    update_time DATETIME NULL,
    remark VARCHAR(500) NULL,
    branch_star_id INT NULL,
    PRIMARY KEY (user_id),
    UNIQUE KEY uk_sys_user_user_name (user_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_message (
    message_id INT NOT NULL AUTO_INCREMENT,
    message_title VARCHAR(50) NOT NULL,
    message_flag CHAR(1) DEFAULT '0',
    message_content VARCHAR(1000) NULL,
    start_date DATE NULL,
    end_date DATE NULL,
    status CHAR(1) DEFAULT '0',
    receive_user_id INT NULL,
    receive_user_name VARCHAR(255) NULL,
    message_file_name VARCHAR(255) NULL,
    message_file_path VARCHAR(1000) NULL,
    message_level VARCHAR(1) DEFAULT '0',
    create_by VARCHAR(64) DEFAULT '',
    create_time DATETIME NULL,
    update_by VARCHAR(64) DEFAULT '',
    update_time DATETIME NULL,
    remark VARCHAR(255) NULL,
    PRIMARY KEY (message_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_feedback (
    id INT NOT NULL AUTO_INCREMENT,
    messageid INT NULL,
    content VARCHAR(1000) NULL,
    create_by VARCHAR(64) DEFAULT '',
    create_time DATETIME NULL,
    update_by VARCHAR(64) DEFAULT '',
    update_time DATETIME NULL,
    remark VARCHAR(255) NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_post (
    post_id BIGINT NOT NULL AUTO_INCREMENT,
    post_code VARCHAR(64) NOT NULL,
    post_name VARCHAR(50) NOT NULL,
    post_sort INT NOT NULL,
    status CHAR(1) NOT NULL,
    create_by VARCHAR(64) DEFAULT '',
    create_time DATETIME NULL,
    update_by VARCHAR(64) DEFAULT '',
    update_time DATETIME NULL,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (post_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
